# This is a basic workflow to help you get started with Actions
name: CD

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_docker:
    name: J1 -> Docker Job
    runs-on: docker-latest
    steps:
      - name: J1S1 -> Docker Step 1
        run: echo Starting Docker

  job_1:
    name: J2 -> DevSecOps Job
    runs-on: ubuntu-latest
    steps:
      - name: J2S1 -> DevSecOps Step 1
        run: echo Starting DevSecOps on Python code

      - name: J2S2 -> DevSecOps Step 2
        run: echo Starting DevSecOps on Flask code