# This is a basic workflow to help you get started with Actions
name: CD/CD (Continuous integration and continuous delivery)

# Controls when the workflow will run
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_build:
    name: Build Job
    runs-on: docker-latest
    steps:
      - name: Compiling the code
        run: echo Compiling the code...
      - name: Compile complete
        run: Compile complete.

  job_security_test_dast:
    name: Security testing DAST
    runs-on: ubuntu-latest
    needs: [job_build]
    steps:
      - name: Security DAST testing
        run: echo Security DAST testing...
